version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pgsql
    environment:
      POSTGRES_DB: pgsql
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
